version: '3.7'

services:  
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
        - "1080:8025"
    networks:
        - php     
  php:
    image: scheffer_shen/php72:latest
    container_name: php
    user: '1000:1000'
    working_dir: /var/www/html
    volumes:
      - "./:/var/www/html"
    networks:
      - mysql
      - php    
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --max_allowed_packet=32505856 
    environment:
      MYSQL_ROOT_PASSWORD: 9TT4fgq5
      MYSQL_DATABASE: keycloak
    volumes:
      - "./docker/.data/db:/var/lib/mysql"
      - "./sql:/home"
    networks:
      - mysql    
  caddy:
    image: caddy:2
    container_name: caddy
    environment:
      SERVER_NAME: ${SERVER_NAME:-lms3.universalmedica.local, caddy:80}
    ports:
      - 80:80
      - 443:443
    working_dir: /var/www/html
    volumes:
      - "./public:/var/www/html/public"    
      - "./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro"
      - "./docker/.data/caddy/data:/data"
      - "./docker/.data/caddy/config:/config"  
    networks:
      - php
  keycloak:
      image: jboss/keycloak
      container_name: keycloak
      ports:
          - "8181:8080"
      environment:
          DB_VENDOR: mysql
          DB_ADDR: mysql
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: 9TT4fgq5
          DB_DATABASE: keycloak
          KEYCLOAK_USER: root
          KEYCLOAK_PASSWORD: root
          KEYCLOAK_IMPORT: '/opt/jboss/keycloak/examples-realm.json'
      networks:
          - mysql
      depends_on:
          - mysql
      volumes:
          - ./realm-export.json:/opt/jboss/keycloak/examples-realm.json  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always    
    ports:
      - "8080:80"      
    environment:
        PMA_HOST: mysql
    networks:
      - mysql   
  
  redis:
    image: redis:5-alpine
    container_name: redis
    restart: always
    #ports: [6379]
    networks:
      - php 

networks:
    php:
        driver: bridge
    mysql:
        driver: bridge      
