version: '3'

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
        - "1080:8025"
    networks:
        - app-network     
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=9TT4fgq5
    volumes: 
      - ./.data/db:/var/lib/mysql
      - ./_SQL:/home
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1.3
    container_name: phpmyadmin
    restart: always    
    ports:
        - 8080:80      
    environment:
        PMA_HOST: db
    networks:
        - app-network 

  php:
    image: scheffer_shen/php74:latest
    container_name: php
    user: '1000:1000'
    working_dir: /var/www/html
    volumes:
      - ./wordpress:/var/www/html
    networks:
        - app-network

  caddy:
    image: caddy:2
    container_name: caddy
    environment:
      SERVER_NAME: ${SERVER_NAME:-sante-sur-le-net.local, caddy:80}
    ports:
      - 80:80
      - 443:443
    working_dir: /var/www/html
    volumes:
      - ./wordpress:/var/www/html
      - ./.caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./.data/caddy/data:/data
      - ./.data/caddy/config:/config

networks:
  app-network:
    driver: bridge